# IME Indicator config

[poll]
state_interval_ms = 100
track_interval_ms = 10

[tray]
enable = true

[caret]
enable = true
color_cn = "#76E3A7A0"
color_en = "#F4C060A0"
size = 16
offset_x = 0
offset_y = 10
show_en = true

[mouse]
enable = true
color_cn = "#76E3A7A0"
color_en = "#F4C060A0"
size = 16
offset_x = -20
offset_y = 18
show_en = true
target_cursors = [32513, 32512]
